version: '3.7'

services:
  rheinjug1:
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app
  database:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=geheim"
      - "MYSQL_DATABASE=Ziegel24"