= Java in der Praxis

== Problemstatement

* Fuer Studierende: Es gibt momentan keine zentrale Stelle/keinen zentralen
Ansprechpartner fuer das Einreichen von Meetup-/Entwickelbar-Zusammenfassungen
gegen CP
* Fuer Dozierende: Er gibt aktuell keine zentrale Verifikation
noch nicht eingereichter Veranstaltungen; dadurch ist das System unsicher und
die Verwaltung aufwaendig
* Es gibt keine Statistiken darueber, welche Veranstaltungen wie oft besucht
werden und zu welchen Zusammenfassungen eingereicht werden

== Wesentliche Ziele und Features

* Java in der Praxis bietet Studierenden die Moeglichkeit, sich fuer
Meetup-Veranstaltungen anzumelden (Rheinjug/Entwickelbar), sowie
Zusammenfassungen fuer besuchte Veranstaltungen hochzuladen
* Dozierende koennen diese Zusammenfassungen durchsehen und die Vergabe von
Credit Points veranlassen
* Das System stellt sicher, dass Studierende nicht fuer Zusammenfassungen
anderer Studierender, und nicht mehrmals fuer dieselbe Zusammenfassung CP
erhalten
* Studierende koennen sich einen Schein fuer ihre CP ausstellen lassen, wenn sie
genug Zusammenfassungen eingereicht haben
* Ziel ist eine komfortable Oberflaeche fuer Anmeldung und Abgabe, zuverlaessige
 Verifikation einloesbarer Quittungen, sowie Flexibilitaet (z.B. nachtraegliches
  Akzeptieren von Abgaben durch Dozierende)
* nicht erforderlich ist, das Ablehnen von Zusammenfassungen zu regeln, da dies
direkt durch den Dozierenden per Mail erfolgt

== Dokumentation

Die Doku ist nach Arc42 gegliedert unter /documentation zu finden.