= Java in der Praxis

== Problemstatement

* Für Studierende: Es gibt momentan keine zentrale Stelle/keinen zentralen
Ansprechpartner für das Einreichen von Meetup-/Entwickelbar-Zusammenfassungen
gegen CP
* Für Dozierende: Er gibt aktuell keine zentrale Verifikation
noch nicht eingereichter Veranstaltungen; dadurch ist das System unsicher und
die Verwaltung aufwändig
* Es gibt keine Statistiken darüber, welche Veranstaltungen wie oft besucht
werden und zu welchen Zusammenfassungen eingereicht werden

== Wesentliche Ziele und Features

* Java in der Praxis bietet Studierenden die Möglichkeit, sich für
Meetup-Veranstaltungen anzumelden (Rheinjug/Entwickelbar), sowie
Zusammenfassungen für besuchte Veranstaltungen hochzuladen
* Dozierende können diese Zusammenfassungen durchsehen und die Vergabe von
Credit Points veranlassen
* Das System stellt sicher, dass Studierende nicht für Zusammenfassungen
anderer Studierender, und nicht mehrmals für dieselbe Zusammenfassung, CP
erhalten
* Studierende können sich einen Schein für ihre CP ausstellen lassen, wenn sie
genug Zusammenfassungen eingereicht haben
* Ziel ist eine komfortable Oberfläche für Anmeldung und Abgabe, zuverlässige
 Verifikation einlösbarer Quittungen, sowie Flexibilität (z.B. nachträgliches
  Akzeptieren von Abgaben durch Dozierende)
* nicht erforderlich ist, das Ablehnen von Zusammenfassungen zu regeln, da dies
direkt durch den Dozierenden per Mail erfolgt

== Dokumentation

Die Doku ist nach Arc42 gegliedert unter /documentation zu finden.